name: utils_well
description: "A new Flutter package project."
version: 0.0.1
homepage: none

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sliver_tools: ^0.2.12
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
