name: utils_well_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  equatable: ^2.0.7

dev_dependencies:
  test: ^1.25.6
